### PR TITLE
Create PlayerList.kt

### PR DESCRIPTION
**Pull request by opZywl**

### CODE REVIEW

**Comment by exit-scammed** [comment]
LOL

**Comment by exit-scammed** [comment]
727/100 code bot

**Comment by opZywl** [comment]
> 727/100 code bot

yoo oh i will leave you credits

**Comment by opZywl** [comment]
I'm not sure if it will be added

**Comment by opZywl** [comment]
update @liulihaocai 
19031D98-D574-4D26-8691-144F3BA63CAE

**Pull request merged**
