### PR TITLE
Update and rename LiquidWalk.kt to Jesus.kt

### PR DESCRIPTION
**Pull request by opZywl**

### CODE REVIEW

**Comment by opZywl** [comment]
Rename and Spartan bypass

**Comment by guimc233** [comment]
Okay

**Comment by liulihaocai** [comment]
no plz this name is not good

**Comment by MCCheatDeveloper** [comment]
jesus > liquidwalk

**Comment by opZywl** [comment]
yes jesus > liquidwalk asuahsausahs

> jesus > liquidwalk

**Comment by opZywl** [comment]
> Okay

it failed, you have to change the LiquidWalk mixin to jesus

**Pull request merged**
