### PR TITLE
Removed skidded material

### PR DESCRIPTION
**Pull request by Tecnio**

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
Everything is skidded from Unicode xD

**Comment by ENDER1355** [comment]
> _No description provided._

+1

**Comment by Nicklas5597** [comment]
cockness

**Comment by liulihaocai** [comment]
lmao

**Comment by ENDER1355** [comment]
> lmao

no

**Comment by ENDER1355** [comment]
> The PR diff size of 77595 lines exceeds the maximum allowed for the inline comments feature.

gay

**Comment by Tecnio** [comment]
Guys unfortunately out PR didn't get merged thanks for watching my video

**Comment by ENDER1355** [comment]
> Guys unfortunately out PR didn't get merged thanks for watching my video

goddamnit why didn't it get accepted

**Comment by ENDER1355** [comment]
> Guys unfortunately out PR didn't get merged thanks for watching my video

fdpclient is zenci

**Comment by NyanCatForEver** [comment]
get real

**Pull request closed without merging**
