### PR TITLE
 TeleportCommand.kt

### PR DESCRIPTION
**Pull request by opZywl**

### CODE REVIEW

**Comment by opZywl** [comment]
add this = become a billionaire $$$$$

**Comment by contionability** [comment]
it just simply setPosition
won't bypass any server I think

**Comment by ll11l1lIllIl1lll** [comment]
> it just simply setPosition
> won't bypass any server I think

bypass jogar.mush.com.br

**Comment by opZywl** [comment]
LMAO this is good 
readd pls It is also well requested

**Comment by opZywl** [comment]
> it just simply setPosition
> won't bypass any server I think

it ignores several servers and of course some do not, but it really works and is very useful on vanilla servers

**Pull request closed without merging**
