### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ali00035**
:trollface:

### CODE REVIEW

**Comment by danik4985** [comment]
ok but like this is the best PR i have ever seen on github why did it get closed?

**Comment by danik4985** [comment]
@contionability stop ignoring your community, this is clearly a wildly requested feature

**Comment by FartCheese** [comment]
> @contionability stop ignoring your community, this is clearly a wildly requested feature

I agree my czech guy

**Comment by FartCheese** [comment]
> ok but like this is the best PR i have ever seen on github why did it get closed?

they like thealtening

**Comment by FartCheese** [comment]
@contionability @liulihaocai Stop ignoring this good PR and merge it with the main branch

**Comment by danik4985** [comment]
@contionability we are waiting...

**Pull request closed without merging**
