### PR TITLE
Update KillAura.kt

### PR DESCRIPTION
**Pull request by opZywl**

### CODE REVIEW

**Comment by opZywl** [comment]
because the right thing is not to exceed 1000 delay and 300 is the default

**Comment by liulihaocai** [comment]
what is **circleRadius**

**Comment by ll11l1lIllIl1lll** [comment]
> what is **circleRadius**

Although not used, it should be useful in the future.
<del> Shitcode Principles: 💩 Create variables that you're not going to use. </del>
<del> 琉璃酱我真的好爱你我想做你的狗啊啊啊 </del>

**Comment by opZywl** [comment]
> what is **circleRadius**

I forgot to import the circles, this is a mark 
hey add the switchdelay fix there that I sent

**Comment by opZywl** [comment]
> > what is **circleRadius**
> 
> I forgot to import the circles, this is a mark
> hey add the switchdelay fix there that I sent

bad failed 
image
anyway and that's what I'm adding or trying hauahsaush

**Pull request closed without merging**
