### PR TITLE
Update KillAura.kt

### PR DESCRIPTION
**Pull request by opZywl**

### CODE REVIEW

**Comment by opZywl** [comment]
wtf failed -' lol check @liulihaocai

**Comment by opZywl** [comment]
I don't understand what failed

**Comment by liulihaocai** [comment]
image
hmm did you use an IDE to code?

**Comment by opZywl** [comment]
> image
> hmm did you use an IDE to code?

I think it will work now, well I do it directly through github

**Comment by liulihaocai** [comment]
no i'll do it myself

**Comment by opZywl** [comment]
> no i'll do it myself

okay yes I've already gone crazy and I don't understand 🤣

**Pull request merged**
